In [1]:
import pandas as pd

x = pd.read_csv('/home/m/dev/ai/scaleout/trainingdata/train.csv', encoding='latin-1')
 
x.drop(columns=['query', 'date', '0', 'user', 'index'], inplace=True)

In [3]:
import os

# Calculate the number of parts
num_parts = len(x) // 10000
remainder = len(x) % 10000

# Create the 'x' directory if it doesn't exist
os.makedirs('x', exist_ok=True)

# Split the dataset into parts of 10,000 entries and write to files
for i in range(num_parts):
    part = x[i*10000:(i+1)*10000]
    part.to_csv(f'x/part_{i+1}.csv', index=False)

# Add the remainder as the last part if it exists
if remainder > 0:
    last_part = x[num_parts*10000:]
    last_part.to_csv(f'x/part_{num_parts+1}.csv', index=False)

print(f"Number of parts: {num_parts + (1 if remainder > 0 else 0)}")
for i in range(num_parts + (1 if remainder > 0 else 0)):
    file_path = f'x/part_{i+1}.csv'
    file_size = os.path.getsize(file_path)
    print(f"Part {i+1} size: {file_size} bytes")

,index,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer. You shoulda got David Carr of Third Day to do it. ;D"
0,0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew
...,...,...,...,...,...,...,...
1599994,1599994,4,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,Just woke up. Having no school is the best fee...
1599995,1599995,4,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,TheWDB.com - Very cool to hear old Walt interv...
1599996,1599996,4,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,Are you ready for your MoJo Makeover? Ask me f...
1599997,1599997,4,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,Happy 38th Birthday to my boo of alll time!!! ...
1599998,1599998,4,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy #charitytuesday @theNSPCC @SparksCharity...